config/routes.rb
Rails.application.routes.draw do

  resources :scenarios do
    collection do
      get 'get-restaurants'
    end
  end

  root 'starter#home'

  get 'configuration' => 'starter#configuration'
  get 'assessor' => 'assessor#home'
  get 'sample' => 'assessor#sample'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simplyawesome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyKaPV4Oq0e5wpcKwyqV-hKolT1Bqc5vs"></script>
  <script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
  <%= javascript_include_tag 'highcharts', 'chartkick' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Simply Awesome</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Application", assessor_path , id: 'application-link' %>
        </li>
        <li>
          <%= link_to scenarios_path do %>
            <i class="fa fa-cog"></i>
          <% end %>
        </li>


      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div id="people-loading" hidden></div>
<div class="container theme-showcase" role="main">

  <%= yield %>

</div>

<footer class="footer">
  <p>© 2016 Simply Awesome</p>
</footer>
<%= javascript_include_tag 'main' %>
<%= javascript_include_tag 'mapInit' %>
</body>
</html>

app/views/layouts/google-layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simplyawesome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.config.google_key %>"></script>
  <script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Simply Awesome</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Application", assessor_path, id: 'application-link' %>
        </li>
        <li>
          <%= link_to scenarios_path do %>
            <i class="fa fa-cog"></i>
          <% end %>
        </li>


      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div id="looking-around" hidden></div>
<div id="people-loading" hidden></div>
<div class="container theme-showcase container-with-map" role="main">

  <%= yield %>

</div>
<div class="google-map-container">
  <div id="google-map"></div>
</div>

<%= javascript_include_tag 'main' %>
<%= javascript_include_tag 'mapInit' %>
</body>
</html>